import type { Component } from 'svelte';
import type Vditor from 'vditor';
import type {
	AppSnapshot,
	ChatMessage,
	GitCommit,
	NoteDocument,
	NoteSummary,
	ProviderStatus,
	SourceAnnotation
} from '$lib/types';
import type { OcrStatus } from '$lib/settings/types';
import type { BlockItem } from '$lib/note-page/types';

export type AsyncAction = (...args: unknown[]) => Promise<void>;
export type SyncAction = (...args: unknown[]) => void;
export type StringAction = (...args: unknown[]) => string | null;
export type RequiredStringAction = (...args: unknown[]) => string;
export type NumberAction = (...args: unknown[]) => number | null;
export type BooleanAction = (...args: unknown[]) => boolean;
export type SessionHandle = Record<string, (...args: unknown[]) => unknown>;
export type SelectionHandle = { captureEditorSelection: () => void };
export type DynamicComponent = Component<never>;

type ActiveSection = { key: string; label?: string; content: string };
type SectionCache = {
	done: number;
	total: number;
	sectionDone: number;
	sectionTotal: number;
	label: string;
	profile: 'shared' | 'chat' | 'write' | '';
	startedAt: number;
	finished: boolean;
	failed: number;
	failedDetails: string[];
	elapsedMs: number | null;
};
type SelectionTarget = {
	text: string;
	before: string;
	after: string;
	cursor: boolean;
	cellIndex?: number;
};
export interface LinkingSessionPort {
	linkNoteDialog: HTMLDialogElement | undefined;
	linkSearchQuery: string;
	linkSearchResults: NoteSummary[];
	linkSelectedIndex: number;
	linkDialogMode: 'notes' | 'blocks';
	selectedNoteForBlocks: NoteDocument | null;
	allNoteBlocks: BlockItem[];
	filteredBlocks: BlockItem[];
	previewNoteDialog: HTMLDialogElement | undefined;
	previewNoteTarget: NoteSummary | null;
	previewNoteContainer: HTMLElement | undefined;
	globalSearchDialog: HTMLDialogElement | undefined;
	globalSearchQuery: string;
	globalSelectedIndex: number;
	globalBlocks: BlockItem[];
	filteredGlobalBlocks: BlockItem[];
	openPreviewModal: SyncAction;
	handleVditorClick: SyncAction;
	handleVditorKeydownCapture: SyncAction;
	handleVditorKeyupCapture: SyncAction;
	handleLinkSearchKeydown: SyncAction;
	autofocus: (node: HTMLElement) => { destroy?: () => void };
	selectNoteForBlocks: AsyncAction;
	insertBlockLink: AsyncAction;
	openGlobalBlockSearch: AsyncAction;
	handleGlobalSearchKeydown: SyncAction;
	insertGlobalBlockLink: AsyncAction;
}
export interface NavigationSessionPort {
	isProgrammaticNavigation: boolean;
	pendingNavigationUrl: string;
	pendingBack: boolean;
}
export interface EditorSessionPort {
	parseBlocks: (markdown: string, sourceNoteId?: string, sourceTitle?: string) => BlockItem[];
	dispose: SyncAction;
}
type DebugTraceEntry = { time: number; msg: string; kind: string };
type DebugInfo = {
	requestStart: number | null;
	firstChunk: number | null;
	generationStart: number | null;
	generationEnd: number | null;
	done: number | null;
	promptTokens: number;
	completionTokens: number;
	totalTokens: number;
	turnCount: number;
	replyChars: number;
	trace: DebugTraceEntry[];
};

/** Typed state ports shared by the note-page sessions. */
export interface NotePageContext {
	note: NoteDocument | null;
	isLoadingNote: boolean;
	draftBody: string;
	draftTitle: string;
	draftTags: string;
	isBusy: boolean;
	message: string;
	latexDownloadMsg: string | null;
	texAutoCompile: boolean;
	texCompiling: boolean;
	texCacheWarmed: boolean;
	texPreviewStatus: 'pending' | 'compiling' | 'current' | 'error' | null;
	texCompileError: string | null;
	texRevision: number;
	texCompileQueued: boolean;
	lastTexBody: string;
	texDiagnostics: { line: number; message: string; severity?: 'error' | 'warning' }[];
	texAutoTimer: ReturnType<typeof setTimeout> | undefined;
	activeSidebarTab: 'info' | 'chat' | 'versions';
	noteHistory: GitCommit[];
	versionPreviewContent: string | null;
	versionPreviewHash: string | null;
	versionPreviewDialog: HTMLDialogElement | undefined;
	chatMessages: ChatMessage[];
	chatPersistenceError: string | null;
	chatInput: string;
	copiedIdx: number | null;
	chatTextareaEl: HTMLTextAreaElement | undefined;
	chatMessagesEl: HTMLDivElement | undefined;
	showDebugWindow: boolean;
	activeAiComposerMode: 'chat' | 'editor' | null;
	activeChatNoteId: string | null;
	aiInteractionMode: 'chat' | 'write';
	activeAiEditTarget: SelectionTarget | null;
	activeAiNoteId: StringAction;
	activeChatRequestId: string | null;
	debugInfo: DebugInfo | null;
	armedSelection: (SelectionTarget & { chars: number; words: number }) | null;
	writeTargetNotice: boolean;
	selDebounce: ReturnType<typeof setTimeout> | undefined;
	noteStreaming: boolean;
	noteStreamBuf: string;
	noteStreamBackup: string;
	noteStreamFlushPending: boolean;
	noteStreamSpan: [number, number] | null;
	savedEditorRange: Range | null;
	shortcutEditorRange: Range | null;
	shouldRefocusEditor: boolean;
	isSourceMaterial: boolean;
	sourceMaterialType: 'pdf' | 'epub' | 'html' | 'txt' | 'docx' | 'rtf' | null;
	workingDocType: 'md' | 'tex' | 'ipynb';
	PdfViewerComponent: DynamicComponent | null;
	EpubViewerComponent: DynamicComponent | null;
	HtmlViewerComponent: DynamicComponent | null;
	TexEditorComponent: DynamicComponent | null;
	IpynbEditorComponent: DynamicComponent | null;
	texEditorInstance: { focusEditor?: () => void } | undefined;
	ipynbEditorInstance: { focusEditor?: () => void } | undefined;
	activeSourceId: string | null;
	activeSourceBytes: Uint8Array | null;
	activeSection: ActiveSection | null;
	sectionCache: SectionCache | null;
	scratchpadSavedId: string | null;
	showAttachedNote: boolean;
	pdfIngestionStatus: 'idle' | 'indexing' | 'cached' | 'indexed' | 'empty' | 'failed';
	pdfIngestionError: string | null;
	pdfIngestionPromise: Promise<void> | null;
	splitRatio: number;
	isResizing: boolean;
	mainLayoutEl: HTMLElement | undefined;
	PANE_MIN_WIDTH: number;
	SIDEBAR_MIN_WIDTH: number;
	sidebarWidth: number;
	isSidebarResizing: boolean;
	vditorContainer: HTMLElement | undefined;
	vditorInstance: Vditor | null;
	VditorConstructor: typeof Vditor | null;
	vditorLoading: boolean;
	toolsReady: boolean;
	fullscreenShortcut: string;
	blockCache: Record<string, string>;
	transclusionObserver: MutationObserver | null;
	toolbarExpanded: boolean;
	toolbarNeedsToggle: boolean;
	toolbarResizeObserver: ResizeObserver | null;
	saveStatus: 'saved' | 'saving' | 'unsaved';
	saveTimer: ReturnType<typeof setTimeout> | null;
	navigationWarningDialog: HTMLDialogElement | undefined;
	deleteAttachedNoteDialog: HTMLDialogElement | undefined;
	deleteMainNoteDialog: HTMLDialogElement | undefined;
	detachPdfDialog: HTMLDialogElement | undefined;
	attachPdfDialog: HTMLDialogElement | undefined;
	pdfSearchQuery: string;
	pdfNotesList: NoteDocument[];
	pdfSelectedIndex: number;
	filteredPdfs: NoteDocument[];
	shouldRenderEditor: boolean;
	shouldInitEditor: boolean;
	loadedRouteNoteId: string;
	MAX_CHAT_RENDER_CACHE: number;
	MAX_DEBUG_MSG_CHARS: number;
	MAX_DEBUG_TRACE: number;
	APPROVAL_TIMEOUT_MS: number;
	approvalTimeouts: Map<string, ReturnType<typeof setTimeout>>;
	chatChunkBuf: string;
	chatChunkFlushPending: boolean;
	chatPersistTimer: ReturnType<typeof setTimeout> | undefined;
	pendingDebugTrace: DebugTraceEntry[];
	localVditorCdn: RequiredStringAction;
	hasReturnTo: BooleanAction;
	openNoteNotebook: StringAction;
	getSelectionTextOffset: NumberAction;
	textOffsetOf: NumberAction;
	nearestIndexOf: NumberAction;
	clearArmedSelection: SyncAction;
	appendToNoteBody: SyncAction;
	triggerAutoSave: SyncAction;
	destroyEditorInstance: SyncAction;
	focusEditor: SyncAction;
	refocusEditorSoon: SyncAction;
	captureShortcutEditorTarget: SyncAction;
	restoreShortcutEditorFocus: SyncAction;
	captureEditorSelection: SyncAction;
	reselectAfterEdit: SyncAction;
	restoreSelectionTextOffset: SyncAction;
	saveCursorPosition: SyncAction;
	insertAtSavedCursor: SyncAction;
	onDocMouseDown: SyncAction;
	handleGlobalSelectionChange: SyncAction;
	openMathDialog: SyncAction;
	updateToolbarOverflow: SyncAction;
	scrollChatToBottom: SyncAction;
	saveNote: () => Promise<void>;
	setSaveNote: (save: () => Promise<void>) => void;
	setSelectionSession: (session: SelectionHandle) => void;
	invalidateVditorInitialization: SyncAction;
	setupTransclusionObserver: SyncAction;
	editorNeedsAuthoritativeBody: BooleanAction;
	persistChatHistory: AsyncAction;
	checkpointChatHistory: SyncAction;
	flushChatChunks: SyncAction;
	fetchRelatedNotes: AsyncAction;
	fetchNoteHistory: AsyncAction;
	loadCurrentNote: AsyncAction;
	refreshCurrentNoteFromBackend: AsyncAction;
	goToHome: SyncAction;
	goToNote: SyncAction;
	goToHref: SyncAction;
	safeNavigate: AsyncAction;
	deleteNote: AsyncAction;
	createDocumentSession: (...args: never[]) => unknown;
	createStreamingSession: (...args: never[]) => unknown;
	createLinkingSession: (...args: never[]) => unknown;
	createEditorSession: (...args: never[]) => unknown;
	createNavigationSession: (...args: never[]) => unknown;
	createSourceSession: (...args: never[]) => unknown;
	createChatSession: (...args: never[]) => unknown;
	editorSession: EditorSessionPort;
	navigationSession: NavigationSessionPort;
	sourceSession: SessionHandle;
	linkingSession: LinkingSessionPort;
	chatSession: SessionHandle;
	aiEventContext: NotePageContext;
	// Cross-session actions exposed by the composition graph.
	applyNoteWrite: (content: string, mode?: string) => void;
	attachPdf: AsyncAction;
	appendNoteStream: (delta: string) => void;
	beginAiRequest: AsyncAction;
	beginNoteStream: SyncAction;
	browseAndAttachPdf: AsyncAction;
	buildPreviewExpandHref: StringAction;
	cancelDeleteAttachedNote: SyncAction;
	cancelNavigation: SyncAction;
	cancelNoteStream: SyncAction;
	closeTexPreview: SyncAction;
	compileTex: AsyncAction;
	confirmDeleteAttachedNote: AsyncAction;
	confirmDetachPdf: AsyncAction;
	confirmNavigation: AsyncAction;
	duplicateNote: AsyncAction;
	debugTimer: ReturnType<typeof setInterval> | null;
	expandPreviewNoteDirect: SyncAction;
	extractChatErrorMessage: StringAction;
	failStreamingChatMessage: AsyncAction;
	finishStreamingChatMessage: AsyncAction;
	flushNoteStream: SyncAction;
	goBack: AsyncAction;
	handleAnnotationsChange: AsyncAction;
	handleBeforeUnload: SyncAction;
	handleChatSidebarShortcut: SyncAction;
	handleGlobalMouseMove: SyncAction;
	stopResizing: SyncAction;
	handleImageExtract: AsyncAction;
	handlePdfSearchKeydown: SyncAction;
	handlePdfTextExtracted: AsyncAction;
	saveSourceAnnotations: (annotations: SourceAnnotation[]) => void;
	handleSourceTextExtracted: (text: string) => Promise<void>;
	initVditor: AsyncAction;
	isChatStreaming: boolean;
	makeDebugTraceEntry: (kind: string, msg: string) => DebugTraceEntry;
	mergeChatTools: SyncAction;
	navigateBack: AsyncAction;
	openAttachPdfDialog: SyncAction;
	openLinkDialog: SyncAction;
	parseLatexError: StringAction;
	pickLatexImage: StringAction;
	previewVersion: AsyncAction;
	reconcileRequestNote: AsyncAction;
	relatedNotes: NoteSummary[];
	requestDeleteAttachedNote: SyncAction;
	requestDetachPdf: SyncAction;
	resolveApproval: (id: string, approved: boolean) => Promise<void>;
	restoreVersion: AsyncAction;
	retryMessage: AsyncAction;
	rewindToSnapshot: AsyncAction;
	scanForTransclusions: AsyncAction;
	scheduleNoteStreamFlush: SyncAction;
	sendChatMessage: AsyncAction;
	sendChatText: AsyncAction;
	setStreamingStatus: (status: string) => void;
	stopActiveChat: AsyncAction;
	stopChat: SyncAction;
	tick: () => Promise<void>;
	userScrolledUp: boolean;
	visibleAiStatus: (kind: string, msg: string) => string | null;
	armedEditTarget: () => SelectionTarget | null;
	requireToolApproval: boolean;
	backUrl: string;
}

/** Minimal home lifecycle port. */
export interface HomeContext {
	app: AppSnapshot | null;
	appVersion: string;
	currentWorkspaceForTasks: string | null;
	indexing: boolean;
	message: string;
	provider: ProviderStatus | null;
	ready: boolean;
	refreshApp: AsyncAction;
	reloadTasks: AsyncAction;
	disposeTasks: SyncAction;
}

/** Settings lifecycle and shortcut state port. */
export interface SettingsContext {
	activeBackend: string | null;
	activeEngine: 'llama_cpp' | 'beellama' | null;
	autoOffload: boolean;
	backendFellBack: boolean;
	backendPreference: string;
	beeDownloadActive: boolean;
	contextSize: number | null;
	currentModelPath: string;
	deterministicTools: boolean;
	download: { backend: string; phase: string; percent: number; message: string } | null;
	downloadableBackends: string[];
	downloadableBeeBackends: string[];
	embedModelPath: string;
	enableJupyterExecution: boolean;
	externalApiKey: string;
	externalBaseUrl: string;
	externalEnabled: boolean;
	externalModel: string;
	extraArgs: string[];
	gpuLayers: number | null;
	latexCache: { warmed: boolean; sizeBytes: number } | null;
	latexDownloadBytes: number;
	latexDownloading: boolean;
	latexError: string;
	llamaCache: { enabled: boolean; sizeBytes: number } | null;
	loadProviderStatus: () => Promise<ProviderStatus>;
	maxTurns: number | null;
	modelProfiles: Record<string, unknown>[];
	normalizeBackendPreference: (value: unknown) => string;
	ocrStatus: OcrStatus | null;
	ohBaseUrl: string;
	ohBinPath: string;
	ohCallOnly: boolean;
	ohMaxCalls: number | null;
	ohNoThink: boolean;
	ohPort: number | null;
	ohPromptTools: boolean;
	ohStrict: boolean;
	ohTemplateKwargs: string;
	ohToolChoice: string;
	ohToolMode: 'auto' | 'native' | 'prompt';
	ohToolTimeout: number | null;
	ohTotalMax: number | null;
	promptCache: boolean;
	quickShortcut: string;
	recommendedThreads: number | null;
	refreshAiConfig: AsyncAction;
	refreshSnapshot: AsyncAction;
	rerankerModelPath: string;
	searxngUrl: string;
	startWithSystem: boolean;
	statusPoll: ReturnType<typeof setInterval> | undefined;
	temperature: number | null;
	thinking: boolean;
	threads: number | null;
	toolGating: boolean;
	topP: number | null;
	quickRecording: boolean;
	quickShortcutError: string;
	chatShortcutRecording: boolean;
	chatShortcutError: string;
}

export type ControllerContext = NotePageContext & HomeContext & SettingsContext;
